package mealplaner.recepies.model;

public enum IngredientType {
	WHITE_MEAT, RED_MEAT, MEAT_PRODUCTS, MILK_EGG_PRODUCTS, 
	FRESH_FRUIT, CANNED_FRUIT, FRESH_VEGETABLES, CANNED_VEGETABLES, 
	SPICE, FLUID, BAKING_GOODS, DRIE_GOODS, OTHER;
}
